### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by yusufferdogan** [Hoshiningen/OpenGL-Template#4]
`CMake Error at cmake/LinkASSIMP.cmake:27 (set_target_properties):
  set_target_properties Can not find target to add properties to: zlibstatic
Call Stack (most recent call first):
  CMakeLists.txt:61 (LinkASSIMP)`

**Comment by martinstarkov** [comment]
Misspelled "include" on https://github.com/Hoshiningen/OpenGL-Template/blob/a4e3b662d5437448324f16235e59c4ded7fb33e7/CMakeLists.txt#L52C5-L52C79
